// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example/v1/service.proto

package examplev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/not-for-prod/proterror/proterror"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Internal      bool                   `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_example_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_example_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_example_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_example_v1_service_proto_rawDescGZIP(), []int{1}
}

type InternalError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalError) Reset() {
	*x = InternalError{}
	mi := &file_example_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalError) ProtoMessage() {}

func (x *InternalError) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalError.ProtoReflect.Descriptor instead.
func (*InternalError) Descriptor() ([]byte, []int) {
	return file_example_v1_service_proto_rawDescGZIP(), []int{2}
}

type PublicError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicError) Reset() {
	*x = PublicError{}
	mi := &file_example_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicError) ProtoMessage() {}

func (x *PublicError) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicError.ProtoReflect.Descriptor instead.
func (*PublicError) Descriptor() ([]byte, []int) {
	return file_example_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *PublicError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_example_v1_service_proto protoreflect.FileDescriptor

const file_example_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18example/v1/service.proto\x12\n" +
	"example.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17proterror/options.proto\")\n" +
	"\vTestRequest\x12\x1a\n" +
	"\binternal\x18\x01 \x01(\bR\binternal\"\x0e\n" +
	"\fTestResponse\"\x18\n" +
	"\rInternalError:\a\x9aA\x04\b\x0e\x10\x01\"(\n" +
	"\vPublicError\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text:\x05\x9aA\x02\b\x0e2n\n" +
	"\x0eExampleService\x12N\n" +
	"\x04Test\x12\x17.example.v1.TestRequest\x1a\x18.example.v1.TestResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/example\x1a\f\x92A\t\n" +
	"\aExampleB\xa8\x01\x92A\x19\x12\x17\n" +
	"\aExample\x12\aExample2\x031.0\n" +
	"\x0ecom.example.v1B\fServiceProtoP\x01Z#polymarket/pkg/example/v1;examplev1\xa2\x02\x03EXX\xaa\x02\n" +
	"Example.V1\xca\x02\n" +
	"Example\\V1\xe2\x02\x16Example\\V1\\GPBMetadata\xea\x02\vExample::V1b\x06proto3"

var (
	file_example_v1_service_proto_rawDescOnce sync.Once
	file_example_v1_service_proto_rawDescData []byte
)

func file_example_v1_service_proto_rawDescGZIP() []byte {
	file_example_v1_service_proto_rawDescOnce.Do(func() {
		file_example_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_v1_service_proto_rawDesc), len(file_example_v1_service_proto_rawDesc)))
	})
	return file_example_v1_service_proto_rawDescData
}

var file_example_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_v1_service_proto_goTypes = []any{
	(*TestRequest)(nil),   // 0: example.v1.TestRequest
	(*TestResponse)(nil),  // 1: example.v1.TestResponse
	(*InternalError)(nil), // 2: example.v1.InternalError
	(*PublicError)(nil),   // 3: example.v1.PublicError
}
var file_example_v1_service_proto_depIdxs = []int32{
	0, // 0: example.v1.ExampleService.Test:input_type -> example.v1.TestRequest
	1, // 1: example.v1.ExampleService.Test:output_type -> example.v1.TestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_v1_service_proto_init() }
func file_example_v1_service_proto_init() {
	if File_example_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_v1_service_proto_rawDesc), len(file_example_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_v1_service_proto_goTypes,
		DependencyIndexes: file_example_v1_service_proto_depIdxs,
		MessageInfos:      file_example_v1_service_proto_msgTypes,
	}.Build()
	File_example_v1_service_proto = out.File
	file_example_v1_service_proto_goTypes = nil
	file_example_v1_service_proto_depIdxs = nil
}
