// Code generated by protoc-gen-ProtError. DO NOT EDIT.

package examplev1

import (
	errors "errors"
	registry "github.com/not-for-prod/proterror/registry"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ==================================================================================== //
// ProtError implementation for message: InternalError
// ==================================================================================== //

func (x *InternalError) Error() string {
	return "InternalError"
}

func (x *InternalError) Is(err error) bool {
	_, ok := err.(*InternalError)
	return ok
}

func (x *InternalError) Code() codes.Code {
	return codes.Code(14)
}

func (x *InternalError) Internal() bool {
	return true
}

func (x *InternalError) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func (x *InternalError) Join(err error) error {
	return errors.Join(x, err)
}

func init() {
	err := &InternalError{}

	if !err.Internal() {
		registry.Instance().Add(err)
	}
}

// ==================================================================================== //
// ProtError implementation for message: PublicError
// ==================================================================================== //

func (x *PublicError) Error() string {
	return "PublicError"
}

func (x *PublicError) Is(err error) bool {
	_, ok := err.(*PublicError)
	return ok
}

func (x *PublicError) Code() codes.Code {
	return codes.Code(14)
}

func (x *PublicError) Internal() bool {
	return false
}

func (x *PublicError) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func (x *PublicError) Join(err error) error {
	return errors.Join(x, err)
}

func init() {
	err := &PublicError{}

	if !err.Internal() {
		registry.Instance().Add(err)
	}
}
