// errors.proto defines the canonical proto-based errors exported by proterror.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proterror/errors.proto

package proterror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cancelled indicates the operation was cancelled (typically by the caller).
type Cancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancelled) Reset() {
	*x = Cancelled{}
	mi := &file_proterror_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancelled) ProtoMessage() {}

func (x *Cancelled) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancelled.ProtoReflect.Descriptor instead.
func (*Cancelled) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{0}
}

// Unknown is a fallback error for unexpected failures.
type Unknown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unknown) Reset() {
	*x = Unknown{}
	mi := &file_proterror_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unknown) ProtoMessage() {}

func (x *Unknown) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unknown.ProtoReflect.Descriptor instead.
func (*Unknown) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{1}
}

// InvalidArgument indicates client specified an invalid argument.
type InvalidArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidArgument) Reset() {
	*x = InvalidArgument{}
	mi := &file_proterror_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidArgument) ProtoMessage() {}

func (x *InvalidArgument) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidArgument.ProtoReflect.Descriptor instead.
func (*InvalidArgument) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{2}
}

// DeadlineExceeded indicates the deadline expired before completion.
type DeadlineExceeded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadlineExceeded) Reset() {
	*x = DeadlineExceeded{}
	mi := &file_proterror_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadlineExceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadlineExceeded) ProtoMessage() {}

func (x *DeadlineExceeded) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadlineExceeded.ProtoReflect.Descriptor instead.
func (*DeadlineExceeded) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{3}
}

// NotFound indicates a requested resource was not found.
type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_proterror_errors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{4}
}

// AlreadyExists indicates the resource that a client attempted to create already exists.
type AlreadyExists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlreadyExists) Reset() {
	*x = AlreadyExists{}
	mi := &file_proterror_errors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlreadyExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlreadyExists) ProtoMessage() {}

func (x *AlreadyExists) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlreadyExists.ProtoReflect.Descriptor instead.
func (*AlreadyExists) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{5}
}

// PermissionDenied indicates the caller does not have permission to execute the specified operation.
type PermissionDenied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDenied) Reset() {
	*x = PermissionDenied{}
	mi := &file_proterror_errors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDenied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDenied) ProtoMessage() {}

func (x *PermissionDenied) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDenied.ProtoReflect.Descriptor instead.
func (*PermissionDenied) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{6}
}

// ResourceExhausted indicates some resource has been exhausted, perhaps a per-user quota.
type ResourceExhausted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceExhausted) Reset() {
	*x = ResourceExhausted{}
	mi := &file_proterror_errors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceExhausted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceExhausted) ProtoMessage() {}

func (x *ResourceExhausted) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceExhausted.ProtoReflect.Descriptor instead.
func (*ResourceExhausted) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{7}
}

// FailedPrecondition indicates operation was rejected because the system is not in a required state.
type FailedPrecondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedPrecondition) Reset() {
	*x = FailedPrecondition{}
	mi := &file_proterror_errors_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedPrecondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedPrecondition) ProtoMessage() {}

func (x *FailedPrecondition) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedPrecondition.ProtoReflect.Descriptor instead.
func (*FailedPrecondition) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{8}
}

// Aborted indicates the operation was aborted, typically due to concurrency issues.
type Aborted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aborted) Reset() {
	*x = Aborted{}
	mi := &file_proterror_errors_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aborted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aborted) ProtoMessage() {}

func (x *Aborted) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aborted.ProtoReflect.Descriptor instead.
func (*Aborted) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{9}
}

// OutOfRange indicates operation was attempted past the valid range.
type OutOfRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutOfRange) Reset() {
	*x = OutOfRange{}
	mi := &file_proterror_errors_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutOfRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutOfRange) ProtoMessage() {}

func (x *OutOfRange) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutOfRange.ProtoReflect.Descriptor instead.
func (*OutOfRange) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{10}
}

// Unimplemented indicates operation is not implemented or not supported/enabled.
type Unimplemented struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unimplemented) Reset() {
	*x = Unimplemented{}
	mi := &file_proterror_errors_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unimplemented) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unimplemented) ProtoMessage() {}

func (x *Unimplemented) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unimplemented.ProtoReflect.Descriptor instead.
func (*Unimplemented) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{11}
}

// Internal indicates internal errors.
type Internal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Internal) Reset() {
	*x = Internal{}
	mi := &file_proterror_errors_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Internal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Internal) ProtoMessage() {}

func (x *Internal) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Internal.ProtoReflect.Descriptor instead.
func (*Internal) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{12}
}

// Unavailable indicates the service is currently unavailable.
type Unavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unavailable) Reset() {
	*x = Unavailable{}
	mi := &file_proterror_errors_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unavailable) ProtoMessage() {}

func (x *Unavailable) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unavailable.ProtoReflect.Descriptor instead.
func (*Unavailable) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{13}
}

// DataLoss indicates unrecoverable data loss or corruption.
type DataLoss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataLoss) Reset() {
	*x = DataLoss{}
	mi := &file_proterror_errors_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataLoss) ProtoMessage() {}

func (x *DataLoss) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataLoss.ProtoReflect.Descriptor instead.
func (*DataLoss) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{14}
}

// Unauthenticated indicates the request does not have valid authentication credentials.
type Unauthenticated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unauthenticated) Reset() {
	*x = Unauthenticated{}
	mi := &file_proterror_errors_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unauthenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unauthenticated) ProtoMessage() {}

func (x *Unauthenticated) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_errors_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unauthenticated.ProtoReflect.Descriptor instead.
func (*Unauthenticated) Descriptor() ([]byte, []int) {
	return file_proterror_errors_proto_rawDescGZIP(), []int{15}
}

var File_proterror_errors_proto protoreflect.FileDescriptor

const file_proterror_errors_proto_rawDesc = "" +
	"\n" +
	"\x16proterror/errors.proto\x12\tproterror\x1a\x17proterror/options.proto\"\x12\n" +
	"\tCancelled:\x05\x9aA\x02\b\x01\"\x10\n" +
	"\aUnknown:\x05\x9aA\x02\b\x02\"\x18\n" +
	"\x0fInvalidArgument:\x05\x9aA\x02\b\x03\"\x19\n" +
	"\x10DeadlineExceeded:\x05\x9aA\x02\b\x04\"\x11\n" +
	"\bNotFound:\x05\x9aA\x02\b\x05\"\x16\n" +
	"\rAlreadyExists:\x05\x9aA\x02\b\x06\"\x19\n" +
	"\x10PermissionDenied:\x05\x9aA\x02\b\a\"\x1a\n" +
	"\x11ResourceExhausted:\x05\x9aA\x02\b\b\"\x1b\n" +
	"\x12FailedPrecondition:\x05\x9aA\x02\b\t\"\x10\n" +
	"\aAborted:\x05\x9aA\x02\b\n" +
	"\"\x13\n" +
	"\n" +
	"OutOfRange:\x05\x9aA\x02\b\v\"\x16\n" +
	"\rUnimplemented:\x05\x9aA\x02\b\f\"\x11\n" +
	"\bInternal:\x05\x9aA\x02\b\r\"\x14\n" +
	"\vUnavailable:\x05\x9aA\x02\b\x0e\"\x11\n" +
	"\bDataLoss:\x05\x9aA\x02\b\x0f\"\x18\n" +
	"\x0fUnauthenticated:\x05\x9aA\x02\b\x10B\x87\x01\n" +
	"\rcom.proterrorB\vErrorsProtoP\x01Z%payin/internal/generated/pb/proterror\xa2\x02\x03PXX\xaa\x02\tProterror\xca\x02\tProterror\xe2\x02\x15Proterror\\GPBMetadata\xea\x02\tProterrorb\x06proto3"

var (
	file_proterror_errors_proto_rawDescOnce sync.Once
	file_proterror_errors_proto_rawDescData []byte
)

func file_proterror_errors_proto_rawDescGZIP() []byte {
	file_proterror_errors_proto_rawDescOnce.Do(func() {
		file_proterror_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proterror_errors_proto_rawDesc), len(file_proterror_errors_proto_rawDesc)))
	})
	return file_proterror_errors_proto_rawDescData
}

var file_proterror_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proterror_errors_proto_goTypes = []any{
	(*Cancelled)(nil),          // 0: proterror.Cancelled
	(*Unknown)(nil),            // 1: proterror.Unknown
	(*InvalidArgument)(nil),    // 2: proterror.InvalidArgument
	(*DeadlineExceeded)(nil),   // 3: proterror.DeadlineExceeded
	(*NotFound)(nil),           // 4: proterror.NotFound
	(*AlreadyExists)(nil),      // 5: proterror.AlreadyExists
	(*PermissionDenied)(nil),   // 6: proterror.PermissionDenied
	(*ResourceExhausted)(nil),  // 7: proterror.ResourceExhausted
	(*FailedPrecondition)(nil), // 8: proterror.FailedPrecondition
	(*Aborted)(nil),            // 9: proterror.Aborted
	(*OutOfRange)(nil),         // 10: proterror.OutOfRange
	(*Unimplemented)(nil),      // 11: proterror.Unimplemented
	(*Internal)(nil),           // 12: proterror.Internal
	(*Unavailable)(nil),        // 13: proterror.Unavailable
	(*DataLoss)(nil),           // 14: proterror.DataLoss
	(*Unauthenticated)(nil),    // 15: proterror.Unauthenticated
}
var file_proterror_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proterror_errors_proto_init() }
func file_proterror_errors_proto_init() {
	if File_proterror_errors_proto != nil {
		return
	}
	file_proterror_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proterror_errors_proto_rawDesc), len(file_proterror_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proterror_errors_proto_goTypes,
		DependencyIndexes: file_proterror_errors_proto_depIdxs,
		MessageInfos:      file_proterror_errors_proto_msgTypes,
	}.Build()
	File_proterror_errors_proto = out.File
	file_proterror_errors_proto_goTypes = nil
	file_proterror_errors_proto_depIdxs = nil
}
