// Code generated by protoc-gen-ProtError. DO NOT EDIT.

package proterror

import (
	registry "github.com/not-for-prod/proterror/registry"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ==================================================================================== //
// ProtError implementation for message: Cancelled
// ==================================================================================== //

func (x *Cancelled) Error() string {
	return "Cancelled"
}

func (x *Cancelled) Is(err error) bool {
	_, ok := err.(*Cancelled)
	return ok
}

func (x *Cancelled) Code() codes.Code {
	return codes.Code(1)
}

func (x *Cancelled) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Cancelled{})
}

// ==================================================================================== //
// ProtError implementation for message: Unknown
// ==================================================================================== //

func (x *Unknown) Error() string {
	return "Unknown"
}

func (x *Unknown) Is(err error) bool {
	_, ok := err.(*Unknown)
	return ok
}

func (x *Unknown) Code() codes.Code {
	return codes.Code(2)
}

func (x *Unknown) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Unknown{})
}

// ==================================================================================== //
// ProtError implementation for message: InvalidArgument
// ==================================================================================== //

func (x *InvalidArgument) Error() string {
	return "InvalidArgument"
}

func (x *InvalidArgument) Is(err error) bool {
	_, ok := err.(*InvalidArgument)
	return ok
}

func (x *InvalidArgument) Code() codes.Code {
	return codes.Code(3)
}

func (x *InvalidArgument) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&InvalidArgument{})
}

// ==================================================================================== //
// ProtError implementation for message: DeadlineExceeded
// ==================================================================================== //

func (x *DeadlineExceeded) Error() string {
	return "DeadlineExceeded"
}

func (x *DeadlineExceeded) Is(err error) bool {
	_, ok := err.(*DeadlineExceeded)
	return ok
}

func (x *DeadlineExceeded) Code() codes.Code {
	return codes.Code(4)
}

func (x *DeadlineExceeded) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&DeadlineExceeded{})
}

// ==================================================================================== //
// ProtError implementation for message: NotFound
// ==================================================================================== //

func (x *NotFound) Error() string {
	return "NotFound"
}

func (x *NotFound) Is(err error) bool {
	_, ok := err.(*NotFound)
	return ok
}

func (x *NotFound) Code() codes.Code {
	return codes.Code(5)
}

func (x *NotFound) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&NotFound{})
}

// ==================================================================================== //
// ProtError implementation for message: AlreadyExists
// ==================================================================================== //

func (x *AlreadyExists) Error() string {
	return "AlreadyExists"
}

func (x *AlreadyExists) Is(err error) bool {
	_, ok := err.(*AlreadyExists)
	return ok
}

func (x *AlreadyExists) Code() codes.Code {
	return codes.Code(6)
}

func (x *AlreadyExists) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&AlreadyExists{})
}

// ==================================================================================== //
// ProtError implementation for message: PermissionDenied
// ==================================================================================== //

func (x *PermissionDenied) Error() string {
	return "PermissionDenied"
}

func (x *PermissionDenied) Is(err error) bool {
	_, ok := err.(*PermissionDenied)
	return ok
}

func (x *PermissionDenied) Code() codes.Code {
	return codes.Code(7)
}

func (x *PermissionDenied) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&PermissionDenied{})
}

// ==================================================================================== //
// ProtError implementation for message: ResourceExhausted
// ==================================================================================== //

func (x *ResourceExhausted) Error() string {
	return "ResourceExhausted"
}

func (x *ResourceExhausted) Is(err error) bool {
	_, ok := err.(*ResourceExhausted)
	return ok
}

func (x *ResourceExhausted) Code() codes.Code {
	return codes.Code(8)
}

func (x *ResourceExhausted) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&ResourceExhausted{})
}

// ==================================================================================== //
// ProtError implementation for message: FailedPrecondition
// ==================================================================================== //

func (x *FailedPrecondition) Error() string {
	return "FailedPrecondition"
}

func (x *FailedPrecondition) Is(err error) bool {
	_, ok := err.(*FailedPrecondition)
	return ok
}

func (x *FailedPrecondition) Code() codes.Code {
	return codes.Code(9)
}

func (x *FailedPrecondition) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&FailedPrecondition{})
}

// ==================================================================================== //
// ProtError implementation for message: Aborted
// ==================================================================================== //

func (x *Aborted) Error() string {
	return "Aborted"
}

func (x *Aborted) Is(err error) bool {
	_, ok := err.(*Aborted)
	return ok
}

func (x *Aborted) Code() codes.Code {
	return codes.Code(10)
}

func (x *Aborted) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Aborted{})
}

// ==================================================================================== //
// ProtError implementation for message: OutOfRange
// ==================================================================================== //

func (x *OutOfRange) Error() string {
	return "OutOfRange"
}

func (x *OutOfRange) Is(err error) bool {
	_, ok := err.(*OutOfRange)
	return ok
}

func (x *OutOfRange) Code() codes.Code {
	return codes.Code(11)
}

func (x *OutOfRange) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&OutOfRange{})
}

// ==================================================================================== //
// ProtError implementation for message: Unimplemented
// ==================================================================================== //

func (x *Unimplemented) Error() string {
	return "Unimplemented"
}

func (x *Unimplemented) Is(err error) bool {
	_, ok := err.(*Unimplemented)
	return ok
}

func (x *Unimplemented) Code() codes.Code {
	return codes.Code(12)
}

func (x *Unimplemented) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Unimplemented{})
}

// ==================================================================================== //
// ProtError implementation for message: Internal
// ==================================================================================== //

func (x *Internal) Error() string {
	return "Internal"
}

func (x *Internal) Is(err error) bool {
	_, ok := err.(*Internal)
	return ok
}

func (x *Internal) Code() codes.Code {
	return codes.Code(13)
}

func (x *Internal) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Internal{})
}

// ==================================================================================== //
// ProtError implementation for message: Unavailable
// ==================================================================================== //

func (x *Unavailable) Error() string {
	return "Unavailable"
}

func (x *Unavailable) Is(err error) bool {
	_, ok := err.(*Unavailable)
	return ok
}

func (x *Unavailable) Code() codes.Code {
	return codes.Code(14)
}

func (x *Unavailable) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Unavailable{})
}

// ==================================================================================== //
// ProtError implementation for message: DataLoss
// ==================================================================================== //

func (x *DataLoss) Error() string {
	return "DataLoss"
}

func (x *DataLoss) Is(err error) bool {
	_, ok := err.(*DataLoss)
	return ok
}

func (x *DataLoss) Code() codes.Code {
	return codes.Code(15)
}

func (x *DataLoss) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&DataLoss{})
}

// ==================================================================================== //
// ProtError implementation for message: Unauthenticated
// ==================================================================================== //

func (x *Unauthenticated) Error() string {
	return "Unauthenticated"
}

func (x *Unauthenticated) Is(err error) bool {
	_, ok := err.(*Unauthenticated)
	return ok
}

func (x *Unauthenticated) Code() codes.Code {
	return codes.Code(16)
}

func (x *Unauthenticated) Status() *status.Status {
	st, _ := status.New(x.Code(), x.Error()).WithDetails(x)
	return st
}

func init() {
	registry.Instance().Add(&Unauthenticated{})
}
