// options.proto defines the annotations used to describe proto-based errors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proterror/options.proto

package proterror

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageOptions provides metadata needed to construct a gRPC status.
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the canonical gRPC code associated with the error message.
	Code          code.Code `protobuf:"varint,1,opt,name=code,proto3,enum=google.rpc.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_proterror_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proterror_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_proterror_options_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetCode() code.Code {
	if x != nil {
		return x.Code
	}
	return code.Code(0)
}

var file_proterror_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1043,
		Name:          "proterror.options",
		Tag:           "bytes,1043,opt,name=options",
		Filename:      "proterror/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional proterror.MessageOptions options = 1043;
	E_Options = &file_proterror_options_proto_extTypes[0]
)

var File_proterror_options_proto protoreflect.FileDescriptor

const file_proterror_options_proto_rawDesc = "" +
	"\n" +
	"\x17proterror/options.proto\x12\tproterror\x1a google/protobuf/descriptor.proto\x1a\x15google/rpc/code.proto\"6\n" +
	"\x0eMessageOptions\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.google.rpc.CodeR\x04code:U\n" +
	"\aoptions\x12\x1f.google.protobuf.MessageOptions\x18\x93\b \x01(\v2\x19.proterror.MessageOptionsR\aoptionsB\x88\x01\n" +
	"\rcom.proterrorB\fOptionsProtoP\x01Z%payin/internal/generated/pb/proterror\xa2\x02\x03PXX\xaa\x02\tProterror\xca\x02\tProterror\xe2\x02\x15Proterror\\GPBMetadata\xea\x02\tProterrorb\x06proto3"

var (
	file_proterror_options_proto_rawDescOnce sync.Once
	file_proterror_options_proto_rawDescData []byte
)

func file_proterror_options_proto_rawDescGZIP() []byte {
	file_proterror_options_proto_rawDescOnce.Do(func() {
		file_proterror_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proterror_options_proto_rawDesc), len(file_proterror_options_proto_rawDesc)))
	})
	return file_proterror_options_proto_rawDescData
}

var file_proterror_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proterror_options_proto_goTypes = []any{
	(*MessageOptions)(nil),              // 0: proterror.MessageOptions
	(code.Code)(0),                      // 1: google.rpc.Code
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_proterror_options_proto_depIdxs = []int32{
	1, // 0: proterror.MessageOptions.code:type_name -> google.rpc.Code
	2, // 1: proterror.options:extendee -> google.protobuf.MessageOptions
	0, // 2: proterror.options:type_name -> proterror.MessageOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proterror_options_proto_init() }
func file_proterror_options_proto_init() {
	if File_proterror_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proterror_options_proto_rawDesc), len(file_proterror_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proterror_options_proto_goTypes,
		DependencyIndexes: file_proterror_options_proto_depIdxs,
		MessageInfos:      file_proterror_options_proto_msgTypes,
		ExtensionInfos:    file_proterror_options_proto_extTypes,
	}.Build()
	File_proterror_options_proto = out.File
	file_proterror_options_proto_goTypes = nil
	file_proterror_options_proto_depIdxs = nil
}
